### PR TITLE
Copy RuleEngine.json to Nuget location.

### LINKED ISSUE #2565: RuleEngine.json is not used with internal Nuget
# Bug Report

## Symptom

`RuleEngine.json` is not a part of NuGet and a warning gets logged. We either need to copy `RuleEngine.json` or set disable its environment variable when Nuget is used. 

<HTML>
<BODY>
<TABLE><TR><TD>Event Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> Time MSec</TD><TD>Process Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>Rest &nbsp;</TD></TR><TR><TD>OpenTelemetry-AutoInstrumentation-StartupHook/Warning</TD><TD>12,574.564</TD><TD>Process(51768) (51768)</TD><TD>ThreadID=&quot;49,272&quot; FormattedMessage=&quot;Rule Engine:Couldn't evaluate OpenTelemetry Instrumentation Evaluation. Exception: System.IO.FileNotFoundException: Could not find file '\tracer-home\net\ruleEngine.json'. File name: '\tracer-home\net\ruleEngine.json' at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) at System.IO.File.InternalReadAllText(String path, Encoding encoding) at System.IO.File.ReadAllText(String path) at OpenTelemetry.AutoInstrumentation.RulesEngine.InstrumentationAssemblyRule.Evaluate() &quot; message=&quot;Rule Engine:Couldn't evaluate OpenTelemetry Instrumentation Evaluation. Exception: System.IO.FileNotFoundException: Could not find file '\tracer-home\net\ruleEngine.json'. File name: '\tracer-home\net\ruleEngine.json' at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) at System.IO.File.InternalReadAllText(String path, Encoding encoding) at System.IO.File.ReadAllText(String path) at OpenTelemetry.AutoInstrumentation.RulesEngine.InstrumentationAssemblyRule.Evaluate()&quot; </TD></TR></TABLE>

</BODY>
</HTML>**

### PR DESCRIPTION
**Pull request by rajkumar-rangaraj**
## Why

Fixes #2565

## Checklist

- ~~[ ] `CHANGELOG.md` is updated.~~
- ~~[ ] Documentation is updated.~~
- ~~[ ] New features are covered by tests.~~

### CODE REVIEW

**Review by pjanotti — APPROVED** [review]
LGTM. However, it needs to add the rules JSON file under the NuGet folder so we are clear when the file is being changed. We have been using this practice for the other build-generated source files.

**Comment by rajkumar-rangaraj** [comment]
> LGTM. However, it needs to add the rules JSON file under the NuGet folder so we are clear when the file is being changed. We have been using this practice for the other build-generated source files.

Are you proposing to move the file from `/nuget/OpenTelemetry.AutoInstrumentation/contentFiles/any/any/RuleEngine.json` to  `/nuget/RuleEngine.json` and update `build-nuget-packages.yml` to pick this file?

**Comment by pjanotti** [comment]
@rajkumar-rangaraj 

I was proposing actually to commit `/nuget/OpenTelemetry.AutoInstrumentation/contentFiles/any/any/RuleEngine.json` to the repo. Although it is a generated file we expect its content to not change unintentionally. If the checked-in file changes during the build CI will fail as it did. This makes any changes to the rules visible to us.

**Comment by Kielek** [comment]
@pjanotti. I think that we should have only one committed copy of this file. If necessary we can add this path to .gitignore list.

**Comment by pjanotti** [comment]
@Kielek @rajkumar-rangaraj I didn't notice that the other copy was already committed. Yes, we just need one copy to be committed. We could even use git symlink for that instead of copying the file and adding it to .gitignore, that said, I'm fine with adding it to .gitignore.

**Review by nrcventura — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Pull request merged**
