### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by pellared**
### Added

- Add support for .NET 7.
- Add support for `OTEL_DOTNET_AUTO_LOGS_ENABLED`.
- Add error log if bytecode instrumentation type is missing all instrumentation methods.
- Plugins can overwrite OpenTelemetry .NET SDK exporters' and instrumentations' options.

### Changed

- Replace `OTEL_DOTNET_AUTO_LOAD_TRACER_AT_STARTUP` with `OTEL_DOTNET_AUTO_TRACES_ENABLED` and `OTEL_DOTNET_AUTO_LOAD_METER_AT_STARTUP` with `OTEL_DOTNET_AUTO_METRICS_ENABLED`.
- Disable OpenTracing by default. OpenTracing can be re-enabled via `OTEL_DOTNET_AUTO_OPENTRACING_ENABLED`.
- GraphQL exceptions are recorded as OTel events.
- `DOTNET_STARTUP_HOOKS` required value changed to `$INSTALL_DIR/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll`.

### Removed

- Remove support for .NET Core 3.1.
- Remove support for `OTEL_DOTNET_AUTO_HTTP2UNENCRYPTEDSUPPORT_ENABLED`.
- Remove support for `OTEL_DOTNET_AUTO_ENABLED`. Use `CORECLR_ENABLE_PROFILING` or `COR_ENABLE_PROFILING` instead.
- Remove support for `OTEL_DOTNET_AUTO_INCLUDE_PROCESSES`.
- Remove traces instrumentation for [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient) as it is not working.

### Fixed

- Fix the IIS registration in the PowerShell script module for Windows Server 2016.
- Fix the IIS unregistration in the PowerShell script module.
- Get rid of unnecessary service restarts during the IIS unregistration, in the PowerShell script module.
- `OTEL_DOTNET_AUTO_TRACES_ENABLED` is also respected by bytecode instrumentations.

### CODE REVIEW

**Comment by pellared** [comment]
I want to give a chance to address https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1623 before releasing.

**Review by Kielek — APPROVED** [review]

**Comment by pellared** [comment]
Giving a chance to address https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1644 before releasing

**Comment by pellared** [comment]
The scripts would need to be updated once https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1661 is merged

**Comment by pellared** [comment]
Testing locally: `nuke Workflow --containers linux`

**Review by Kielek — APPROVED** [review]
PR looks good. Please confirm behavior for `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper`.

**Comment by pellared** [comment]
> PR looks good. Please confirm behavior for `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper`.

@Kielek we get following log, but the application does not crash:

```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[11]
      Hosting startup assembly exception
      System.InvalidOperationException: Startup assembly OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper failed to execute. See the inner exception for more details.
       ---> System.IO.FileNotFoundException: Could not load file or assembly 'OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
         at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
         at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
         --- End of inner exception stack trace ---
```

I think it is good enough. Do you agree?

**Review by Kielek — APPROVED** [review]

**Comment by pellared** [comment]
Testing the release workflow before merging: https://github.com/pellared/opentelemetry-dotnet-instrumentation/actions/runs/3540850200

**Pull request merged**
