### PR TITLE
Rename Tests Collection and Fixture types

### PR DESCRIPTION
**Pull request by Kielek**
## Why

Fixes N/A
Better namings for test classes.

## What

`NpgqslCollection` ~> `PostgresCollection`.
Test itself should be called NpgqslTests. We are testing library, but we are using Postgres as a docker.

## Tests

CI

## Checklist

- ~~[ ] `CHANGELOG.md` is updated.~~
- ~~[ ] Documentation is updated.~~
- ~~[ ] New features are covered by tests.~~

### CODE REVIEW

**Review by pellared — COMMENTED** [review]
From a logical perspective, this PR makes sense. But I think that using `NpgsqlCollection` makes it more maintainable b/c it is easier to find as it follows the pattern `xyzTests` and `xyzCollection`.

I would prefer to keep the existing naming but I am not blocking this PR as well 😉

**Comment by Kielek** [comment]
You can expect more similar differences: `StackExchangeRedisTests` and `RedisCollection`, etc.

I think, in this PR we should agree on the convention.

Each test contains reference to the collection, so it is pretty easy to map it.

BTW I have similar doubts related to this naming.

**Comment by pellared** [comment]
If we change `SqlClientCollection` to `SqlServerCollection` then I am fine with this PR 😉

**Comment by pellared** [comment]
I think we could consider also renaming the `xyzCollection.cs` filenames to `xyzCollectionFixture.cs` as 

1. they contain both the `ICollectionFixture` and `Fixture` implementation
2. it would indicate that it is a "CollectionFixture" :smile:

**Review by pellared — APPROVED** [review]

**Pull request merged**
