### PR TITLE
Fixed 2 nits on the code generated by the SourceGenerator

### PR DESCRIPTION
**Pull request by pjanotti**
## Why

Give the generated file a standard code format.

## What

Fixed 2 nits on the generated code.

## Tests

N/A

## Checklist

~~- [ ] `CHANGELOG.md` is updated.~~
~~- [ ] Documentation is updated.~~
~~- [ ] New features are covered by tests.~~

### CODE REVIEW

**Comment by Kielek** [comment]
I think that it it not leftover.
It is a new feature introduced by last upstream native code synce. It is needed to add support for #1126

If you want to remove, you should also remove native method for derived classes.

**Review by Kielek — CHANGES_REQUESTED** [review]
I think that it it not leftover.
It is a new feature introduced by last upstream native code synce. It is needed to add support for #1126

If you want to remove, you should also remove native method for derived classes.

Nit changes are fine :)

**Comment by Kielek** [comment]
One more things. `GetDerivedDefinitions` should be generated by SourceGenerator in the future, but as we do not have any such instrumentation I have skipped this part.

**Comment by pjanotti** [comment]
Edit the title and description to correctly reflect that now this is only changing the generated code.

**Review by nrcventura — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Pull request merged**
