### PR TITLE
Remove Vendored.System.Diagnostics.DiagnosticSource.Tests

### PR DESCRIPTION
**Pull request by pellared**
## Why

Addresses https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/49
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/48/files#r575376172

## What

- Remove `Vendored.System.Diagnostics.DiagnosticSource.Tests.csproj`

### CODE REVIEW

**Review by pjanotti — APPROVED** [review]
LGTM. Next to remove from master is OpenTelemetry.DynamicActivityBinding/OpenTelemetry.DynamicActivityBinding.sln

**Comment by pellared** [comment]
> DynamicActivityBinding

In the same PR or in another one?

**Comment by pellared** [comment]
> LGTM. Next to remove from master is OpenTelemetry.DynamicActivityBinding/OpenTelemetry.DynamicActivityBinding.sln

In the same PR or another one?

**Review by nrcventura — APPROVED** [review]

**Comment by pjanotti** [comment]
@pellared 
> In the same PR or another one?

A separate PR is better.

**Comment by pjanotti** [comment]
Test failure on Windows, kicking it again:
```
2021-02-18T17:22:20.3023003Z [xUnit.net 00:00:05.1239338]     Datadog.Trace.Tests.DogStatsDTests.Send_metrics_when_enabled [FAIL]
2021-02-18T17:22:20.5038720Z   Failed Datadog.Trace.Tests.DogStatsDTests.Send_metrics_when_enabled [2 s]
2021-02-18T17:22:20.5079131Z   Error Message:
2021-02-18T17:22:20.5084087Z    Moq.MockException : 
2021-02-18T17:22:20.5086794Z Expected invocation on the mock once, but was 2 times: s => s.Increment("datadog.tracer.api.requests", 1, 1, null)
2021-02-18T17:22:20.5096347Z No setups configured.
2021-02-18T17:22:20.5097429Z 
2021-02-18T17:22:20.5098725Z Performed invocations: 
2021-02-18T17:22:20.5100551Z IDogStatsd.Gauge("datadog.tracer.heartbeat", 19, 1, null)
2021-02-18T17:22:20.5108493Z IDogStatsd.Increment("datadog.tracer.queue.enqueued_traces", 1, 1, null)
2021-02-18T17:22:20.5110880Z IDogStatsd.Increment("datadog.tracer.queue.enqueued_spans", 1, 1, null)
2021-02-18T17:22:20.5112565Z IDogStatsd.Increment("datadog.tracer.queue.dequeued_traces", 1, 1, null)
2021-02-18T17:22:20.5116857Z IDogStatsd.Increment("datadog.tracer.queue.dequeued_spans", 1, 1, null)
2021-02-18T17:22:20.5121653Z IDogStatsd.Gauge("datadog.tracer.queue.max_traces", 1000, 1, null)
2021-02-18T17:22:20.5125065Z IDogStatsd.Increment("datadog.tracer.api.requests", 1, 1, null)
2021-02-18T17:22:20.5131690Z IDogStatsd.Increment("datadog.tracer.api.errors", 1, 1, null)
2021-02-18T17:22:20.5133368Z IDogStatsd.Increment("datadog.tracer.api.requests", 1, 1, null)
2021-02-18T17:22:20.5134686Z   Stack Trace:
2021-02-18T17:22:20.5136188Z      at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
2021-02-18T17:22:20.5137945Z    at Moq.Mock.VerifyCalls(Mock targetMock, MethodCall expected, Expression expression, Times times)
2021-02-18T17:22:20.5139508Z    at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
2021-02-18T17:22:20.5141409Z    at Moq.Mock`1.Verify(Expression`1 expression, Times times)
2021-02-18T17:22:20.5145088Z    at Datadog.Trace.Tests.DogStatsDTests.Send_metrics_when_enabled() in D:\a\1\s\test\Datadog.Trace.Tests\DogStatsDTests.cs:line 69
2021-02-18T17:22:59.9466349Z Results File: D:\a\_temp\VssAdministrator_WIN-ET9D7OM2JMO_2021-02-18_17_22_17.trx
2021-02-18T17:22:59.9485363Z 
2021-02-18T17:22:59.9568339Z Failed!  - Failed:     1, Passed:   401, Skipped:     1, Total:   403, Duration: 45 s - Datadog.Trace.Tests.dll (netcoreapp3.1)
```

**Comment by pjanotti** [comment]
I confirmed that this won't affect merging where we did the `Activity` wrapper.

**Pull request merged**
