### PR TITLE
[WIP] Update MongoDB driver

### PR DESCRIPTION
**Pull request by RassK**
Updates MongoDB driver to resolve deprecated OP codes issue.

### CODE REVIEW

**Comment by pellared** [comment]
How about pinning the MongoDB docker container version instead of using `latest`?

**Comment by RassK** [comment]
> How about pinning the MongoDB docker container version instead of using `latest`?

Unfortunately in Windows it's baked into the image instead. But there should be no issues moving to container based server.

**Comment by nrcventura** [comment]
What I'm not understanding is why I don't see the same issues locally. The CI pipeline and our local machines should be pulling the same container image and using the same driver version.

**Comment by RassK** [comment]
> What I'm not understanding is why I don't see the same issues locally. The CI pipeline and our local machines should be pulling the same container image and using the same driver version.

Except they didn't release 5.1 in Docker yet, but GH team upgraded the integrated version. Maybe there is even product difference Enterprise vs Community.

**Comment by RassK** [comment]
I'm going to close this as now important right now.

**Pull request closed without merging**
