### PR TITLE
Update .NET version

### PR DESCRIPTION
**Pull request by pellared**
## Why

Maintenance

## What

- Update .NET 5.0 SDK version and use .NET 3.1 runtime instead of SDK in Azure Pipelines where possible.
- Update REAMDE.md.

### CODE REVIEW

**Comment by pellared** [comment]
I will take a look at the issues in CI tomorrow

**Review by dszmigielski — APPROVED** [review]

**Comment by pjanotti** [comment]
Various failures on Windows x64 Integration tests https://dev.azure.com/opentelemetry/4385971a-2f03-4dea-bf49-624c15b8f452/_apis/build/builds/2719/logs/110 kicking it again.

**Review by pjanotti — APPROVED** [review]
LGTM @pellared

**Review by zacharycmontoya — APPROVED** [review]
LGTM!

**Pull request merged**
