### PR TITLE
Upstream sync 2021-05-31

### PR DESCRIPTION
**Pull request by pellared**
## New Issues

Some integration tests are failing. I do not think anything of it is a blocker so I created dedicated issues to track them:

- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/191
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/192

## Upstream changes

commit bd2eba74484908e2d53731463faa70b7b8bb6625
Author: Kevin Gosse <krix33@gmail.com>
Date:   Fri May 28 18:04:22 2021 +0200

Remove the static collection in the HTTP module (https://github.com/DataDog/dd-trace-dotnet/pull/1498)
    
    * Remove the static collection in the HTTP module

---

commit 05e04e8ab20d47c5a6547661068e275c4fcc58c1
Author: Kevin Gosse <krix33@gmail.com>
Date:   Fri May 28 16:20:20 2021 +0200

Add runtime-id tag to metrics (https://github.com/DataDog/dd-trace-dotnet/pull/1496)

---

commit 2e2b9166db11802500896333d8ba9d017fec1fd0
Author: Kevin Gosse <krix33@gmail.com>
Date:   Thu May 27 18:12:16 2021 +0200

Optimize log4net and refactor log providers (https://github.com/DataDog/dd-trace-dotnet/pull/1489)

---

commit 93c0b69001162127c93ab6af3017f25d00852510
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Thu May 27 14:44:34 2021 +0200

Fixes .vcxproj file for latest msbuild version. (https://github.com/DataDog/dd-trace-dotnet/pull/1495)

---

commit a42fde0d17cff1d4dbccc8922377fee013dbb11d
Author: Zach Montoya <zach.montoya@datadoghq.com>
Date:   Wed May 26 09:42:36 2021 -0700

Refactor DisposeWithException invocations to remove null conditional operator ?. (https://github.com/DataDog/dd-trace-dotnet/pull/1493)

---

commit c06a11971299ee1348c2de27b5435fe78fe783ab
Author: Andrew Lock <andrew.lock@datadoghq.com>
Date:   Wed May 26 16:10:38 2021 +0100

Convert ASP.NET tests to use Snapshot Testing with VerifyTests/Verify (https://github.com/DataDog/dd-trace-dotnet/pull/1454)
    
    * Add required gitignore for Verify received files
    
    These should never be checked in (in contrast to *.verified.* files
    
    * Install Verify and update Newtonsoft Json
    
    Json.NET update required as Verify depends on 13.0.1
    
    * Add ModuleInitializerAttribute for < .NET 5
    
    Lets us use C# 9 Module Initializers on < .NET 5
    
    * Ensure sample apps have a consistent environment across machines
    
    * Populate $(SolutionDir) property if not already set
    
    * Add some helpers for verifying MockTracerAgent.Spans
    
    We may need to add additional scrubbers etc.
    In addition to the built-in scrubbers, I'm
    - Excluding the variable duration/start fields
    - Fixing localhost ports to all be :0000
    - Fixing the _dd.tracer_kr: 1.0
    
    Also adds helper for fetching the web spans (without asserting), and for sanitising paths for use in filenames
    
    * Convert AspNetMvc4 tests to use Snapshot testing
    
    * Convert AspNetMvc5 tests to use Snapshot testing
    
    * Convert AspNetWebApi2 tests to use Snapshot testing
    
    * Include architecture in the file name for aspnetcore tests
    
    The stack traces are different depending on architecture.
    There's a PR in to Verify to support this OOTB: https://github.com/VerifyTests/Verify/pull/367
    
    * Add x64 Snapshots
    
    * Add x86 Snapshots
    
    * Add copyright headers
    
    * Fix CI app tests

---

commit 0eb0dd3727d1a62a0fd64cf2c201c152139f27ca
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Wed May 26 11:44:44 2021 +0200

Adds ARM64 throughput test (https://github.com/DataDog/dd-trace-dotnet/pull/1490)
    
    * Initial work to arm64 crank support.
    
    * pipeline changes.

---

commit 896b97ca34dd62a5ec1ea4fb81ba92a6b1a898c4
Author: Andrew Lock <andrew.lock@datadoghq.com>
Date:   Wed May 26 08:58:39 2021 +0100

Add restart policy to Kafka containers (https://github.com/DataDog/dd-trace-dotnet/pull/1492)
    
    The broker has a tendency to fall over, try and handle that

---

commit ed31f829196e1fb4da3752f5617d63a4869df28f
Author: Andrew Lock <andrew.lock@datadoghq.com>
Date:   Wed May 26 08:57:55 2021 +0100

Add GH Action to auto-create benchmark branch (https://github.com/DataDog/dd-trace-dotnet/pull/1483)
    
    When we push a tag, we want to auto-create the benchmarks branch. This should extract the version number for the tag, and create a corresponding benchmarks branch. The benchmarks branches are used by CI to show historical performance.
    
    We use a branch instead of keying directly off the tags, as we don't want to benchmark _every_ release, and so we can delete branches if applicable.

---

commit d1e68d9500f530f4e0ef3b7b4a19619ab96b76a0
Author: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>
Date:   Tue May 25 21:40:47 2021 -0400

Clean up project files (reduce conditionals and reference assemblies) (https://github.com/DataDog/dd-trace-dotnet/pull/1468)
    
    * remove all references to nuget package Microsoft.NETFramework.ReferenceAssemblies
    
    * remove most <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">
    
    * remove <PublicSign>
    
    * remove redundant props file
    
    * only build this project on netfx
    
    * use default targets in test dependencies

---

commit 13ee2e4ed79dfa9332b2aa8a916899d2d5b43a01
Author: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>
Date:   Tue May 25 18:30:03 2021 -0400

Skip building Samples.OracleMDA.* projects (https://github.com/DataDog/dd-trace-dotnet/pull/1477)
    
    * remove unused Samples.OracleMDA and Samples.OracleMDA.Core from build scripts
    * run GeneratePackageVersions tool

---

commit 41d2351408ea68d603d67a5abc4b1271b262b2c5
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Tue May 25 17:38:10 2021 +0200

Temporal skip to avoid flakiness in xunit 2.2.0 test. (https://github.com/DataDog/dd-trace-dotnet/pull/1488)

---

commit c413cd2f5aac4617857727c1a3c1239cc93585bf
Author: Kevin Gosse <krix33@gmail.com>
Date:   Tue May 25 16:51:27 2021 +0200

Add DuckInclude attribute (https://github.com/DataDog/dd-trace-dotnet/pull/1487)

---

commit 974304b417f58216cde58f0edcfc571e21bae9ce
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Tue May 25 14:48:06 2021 +0200

_dd.origin tag improvements. (https://github.com/DataDog/dd-trace-dotnet/pull/1481)
    
    * Initial works on including the _dd.origin tag on all spans and internal api.
    
    * Fixes unit tests
    
    * Adds Benchmark tests.
    
    * performance improvements.
    
    * Benchmark warmup.
    
    * changes
    
    * Add unit tests.
    
    * Fixes test integrations test suite including the new _dd.origin tag.
    
    * Fix MSTest origin tag.
    
    * Change encoding object.
    
    * Removes unnecessary condition
    
    * Update test/benchmarks/Benchmarks.Trace/AgentWriterBenchmark.cs
    
    Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>
    
    * Fix tests.
    
    Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>

---

commit 233450572a04d76a2ea6986050d7e5e08db73cf7
Author: Kevin Gosse <krix33@gmail.com>
Date:   Tue May 25 13:15:55 2021 +0200

Add missing headers (https://github.com/DataDog/dd-trace-dotnet/pull/1485)

---

commit 73cb9743de9b4c4640d5b7768546fb6819da45da
Author: Kevin Gosse <krix33@gmail.com>
Date:   Tue May 25 12:13:32 2021 +0200

Optimize log injection with NLog (https://github.com/DataDog/dd-trace-dotnet/pull/1475)

---

commit b68cdfef714b378cd61ced1fa2894e0e215d90a9
Author: Zach Montoya <zach.montoya@datadoghq.com>
Date:   Mon May 24 16:46:56 2021 -0700

Add and enforce copyright headers for C# files under /build, /src, and /tools (https://github.com/DataDog/dd-trace-dotnet/pull/1445)
    
    - Modifies stylecop rules to enforce copyright headers on C# files
    - Runs the automated rule to add the missing copyright headers
    - Affects all subdirectories EXCEPT /test, which currently doesn't have stylecop applied

---

commit e19c7f4af089ed4edd6a27631bb70bcd0a0b9eb9
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Mon May 24 16:08:08 2021 +0200

MessagePack Formatter: Cache Span tag keys in UTF8 (https://github.com/DataDog/dd-trace-dotnet/pull/1482)

---

commit 83f70e7c1629cb6b083787619e5e45d0ecbebded
Author: Andrew Lock <andrew.lock@datadoghq.com>
Date:   Mon May 24 09:36:04 2021 +0100

Add kafka instrumentation (https://github.com/DataDog/dd-trace-dotnet/pull/1444)
    
    * Add Kafka sample
    
    Demonstrates multiple producers, multiple consumers, auto commit, manual commit tombstones etc
    
    * Add docker-compose entries for running Kafka
    
    Based on https://github.com/confluentinc/cp-all-in-one/blob/6.1.1-post/cp-all-in-one/docker-compose.yml
    Run the full kafaka services using: docker-compose up kafka-control-center kafka-rest-proxy
    Visit the Confluent Control Center at http://localhost:9021/
    
    Note that I omitted the ksqldb and connect services
    
    Added wait-for-it to integration test scripts and added to sample build scripts
    
    * Add Kafka integration
    
    Supports version 1.4.x-2.0.0 (May need to be careful there, internal API changed significantly in 1.4.x, so it could happen again)
    
    Handles async producer, sync producer (with delivery handler), sync producer (no delivery handler), and consumer.
    
    Span context is propagated from producer to consumer using headers, but due to the API design for consumers, we immediately close the span after creation, meaning work that _uses_ that Kafka record won't be using the span,
    
    * Add tests for Kafka integration and helpers
    
    * Finish KafkaHeadersCollectionAdapter implementation
    
    Add Remove support and fix Set implementation
    
    * Redesign consumer integration to assume a canonical setup, and thereby allow propagating scope
    
    * Fix use injected tracer in KafkaHelper
    
    * Update integrations.json
    
    * Add setting to allow disabling the creation of "long-lived" consumer scopes
    
    This may be necessary for customers that are using more complex patterns of consumers, other than the "single-topic in a while loop" approach
    
    * Both consumers may consume a message, leading to "duplicate" spans
    
    This is a Kafka design issue though, rather than an instrumentation issue - those consumes are correct, so we expect _at least_ x spans to be generated for consumers.

---

commit acfa22717baa962080c5814e80f427cc9df208ef
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Fri May 21 17:40:37 2021 +0200

CIApp: Testing frameworks integrations test suite and fixes (https://github.com/DataDog/dd-trace-dotnet/pull/1317)
    
    * Initial Samples projects structure.
    
    * Initial xunit test suite with simple tests.
    
    * Add XUnit Traits test
    
    * Adding more tests.
    
    * enable detailed logs
    
    * Changes.
    
    * debugging info.
    
    * change
    
    * Adds NUnit Test suite and fixes the cases when a test parameterized is skipped reporting different number of tests than console.
    
    * Fix TestProperties on MsTest integration
    
    * changes.
    
    * Fix Parameterized tests on MsTestV2 integration.
    
    * Fix MSTestV2 basic test suite.
    
    * The issue with the XUnit test was that it relied on importing the file xunit.runner.visualstudio/<version>/build/<TFM>/xunit.runner.visualstudio.props (I'm guessing to place xunit.runner.visualstudio.dotnetcore.testadapter.dll in the output directory), but it was not imported because the Import evaluation for the Publish MSBuild Task occurred before the Restore MSBuild Task finished. The unoptimized solution for now is to invoke MSBuild twice. This requires two separate MSBuild processes to start up and might cause accidental rebuilds, but it works for now.
    
    * Changes.
    
    * change test projects.
    
    * Fix integration for Skip parameterized tests.
    
    * Ignore unrelated spans.
    
    * Changes.
    
    * Write spans on errors.
    
    * fix.
    
    * check the nunit version when running in net5.0
    
    * changes.
    
    * Write ProcessId and TargetProcessId
    
    * update integrations.json
    
    * Remove the inlining case.
    
    * Fix Arm64 build and Add debug flag to the test integrations test cases.
    
    * Add more debug flags.
    
    * remove the logger.
    
    * Adding environmental information of the test suite project.
    
    * Remove ambiguity of Category attribute.
    
    * Add NUnitTestAssemblyRunner.WaitForCompletion integration.
    
    * Fix integration
    
    * fix integrations.json
    
    * Fixes the NUnit .NET 5 test case issue.
    
    * Refactor test integrations and Add integration to XUnitTestAssemblyRunner.RunAsync.
    
    * Logging flush.
    
    * Adding Thread.Sleep to the span flush due the agentwriter behavior.
    
    * Refactor internal flushspans logic.
    
    * update integrations.json
    
    * update integrations.json
    
    * Avoiding any syncronization issues due Async over Sync
    
    * Removing unnecessary SyncronizationContext switching
    
    * Move the test tracer creation out of the .cctor
    
    * Try "methodDisplay" = "method" value in the xunit.runner
    
    * Update test/Datadog.Trace.TestHelpers/EnvironmentHelper.cs
    
    Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>
    
    * Solves support for test name with only method name.
    
    * Force foreground thread to block process exit to ensure flushing.
    
    * Addressing PR comments.
    
    * Final changes.
    
    * Addressing PR comments for callsite.
    
    Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>
    Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

---

commit 0efe88c6c81806284a1b395e1586ae871332190e
Author: Kevin Gosse <krix33@gmail.com>
Date:   Fri May 21 17:29:18 2021 +0200

Enable classic mode in IIS tests (https://github.com/DataDog/dd-trace-dotnet/pull/1462)
    
    * Enable classic mode in IIS tests

---

commit 91196b609f3f39beabb70c72c1de1f8fc2072400
Author: Colin Higgins <colin-higgins@users.noreply.github.com>
Date:   Tue May 18 22:24:16 2021 -0400

AAS - Exclude URLs from Tracing (https://github.com/DataDog/dd-trace-dotnet/pull/1447)

---

commit f09e02860cd5686329ac4040e2cd311496aadb6a
Author: Jay C. Davé <7599081+jaycdave88@users.noreply.github.com>
Date:   Tue May 18 11:48:46 2021 -0700

add Windows container sample (https://github.com/DataDog/dd-trace-dotnet/pull/1472)
    
    * PR for Windows Container example
    
    * Update samples/WindowsContainer/README.md
    
    Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>
    
    * Update samples/WindowsContainer/Dockerfile
    
    Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>
    
    * updated based on PR comments
    
    * removing wwwroot/lib
    
    * removed layout & moved to cdn
    
    * setup for automatic tracer version updates
    
    Co-authored-by: jay.dave <jay.dave@JDatadog.local>
    Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

---

commit 989753bab9eaec4db19d687812a5b7eb9734812d
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Mon May 17 19:56:42 2021 +0200

Fix Call opcode in DuckTyping on struct targets. (https://github.com/DataDog/dd-trace-dotnet/pull/1469)
    
    * Call/CallVirt Opcode fix when the target object is an struct (InProperties).
    
    * Change `CallVirt` to `Call` when target object is a ValueType.

---

commit f822b9430840c85cc09540ddd337f988e0bbd3e5
Author: Anna <anna.yafi@datadoghq.com>
Date:   Mon May 17 18:37:07 2021 +0200

Msmq  integration, taking into account all comments from PR #1457. (https://github.com/DataDog/dd-trace-dotnet/pull/1463)
    
    * msmq integration
    
    Co-authored-by: anna-git <anna,yafi@datadoghq.com>

---

commit 5ba7611b5a1c383109cd9152935199db027b0225
Author: Tony Redondo <tony.redondo@datadoghq.com>
Date:   Fri May 14 11:16:08 2021 +0200

Complete ARM64 support (https://github.com/DataDog/dd-trace-dotnet/pull/1449)
    
    * Initial native checks for ARM64 and ARM.
    
    * Comparing ICorProfilerCallback10 uuid for arm architecture.
    
    * Change the GUID type to IID
    
    * Fix compilation issue.
    
    * Print GUID.
    
    * Fix for linux
    
    * changes.
    
    * Revert class_factory.cpp modifications.
    
    * Add test for .NET 5.0 runtime on ARM/ARM64 architectures.
    
    * Fixes force calltarget.
    
    * Change the behavior from force calltarget to enable calltarget by default.
    
    * Include ARM64 build into the packages pipeline.
    
    * Fix packages pipeline
    
    * Adds ARM64 build to dotnet tool/cli
    
    * chmod +x package.arm64.sh
    
    * publish ddtrace arm64 standalone version.
    
    * Add ARM64 build to proj file.
    
    * change arm64 folder readme.
    
    * Includes package.arm64.sh to SetAllVersions.cs file
    
    * Simplify package pipeline for Linux X64 and Arm64 build.
    Include calculated architecture in the unsupported error message of the dotnet tool.
    
    * Removes package.arm64.sh from the SetAllVersion tool.
    
    * Trying to fix `The ARCHITECTURE variable is not set. Defaulting to a blank string` message.
    
    * Addressing PR comments.
    
    * fix package.sh typo

### CODE REVIEW

**Comment by pellared** [comment]
@open-telemetry/dotnet-instrumentation-approvers
I hope this will pass.  I will be back at work on Friday so anyone can pick it up before I am back.

**Comment by zacharycmontoya** [comment]
FYI this Datadog PR added a copyright rule to stylecop so all of the .cs files in the project (except in the test directory) have a Datadog copyright and text field. I'd suggest in this PR to modify the rule in `stylecop.json` to whichever rules you'd like for OpenTelemetry and re-run:  https://github.com/DataDog/dd-trace-dotnet/pull/1445

**Comment by pellared** [comment]
> FYI this Datadog PR added a copyright rule to stylecop so all of the .cs files in the project (except in the test directory) have a Datadog copyright and text field. I'd suggest in this PR to modify the rule in `stylecop.json` to whichever rules you'd like for OpenTelemetry and re-run: [DataDog/dd-trace-dotnet#1445](https://github.com/DataDog/dd-trace-dotnet/pull/1445)

IANAL. However, AFAIK it would violate Datadog's Apache 2 License.

**Comment by pellared** [comment]
I have spent a few hours trying to find out why Integration tests are hanging.

Is there any easy way to:
1. Know which integration test is hanging
2. Debug integration tests

I tried setting `"longRunningTestSeconds" : 10` in `test/Datadog.Trace.ClrProfiler.IntegrationTests/xunit.runner.json` but does not work for unknown reasons.

I have made a manual E2E test and everything was working.

**Comment by zacharycmontoya** [comment]
> > FYI this Datadog PR added a copyright rule to stylecop so all of the .cs files in the project (except in the test directory) have a Datadog copyright and text field. I'd suggest in this PR to modify the rule in `stylecop.json` to whichever rules you'd like for OpenTelemetry and re-run: [DataDog/dd-trace-dotnet#1445](https://github.com/DataDog/dd-trace-dotnet/pull/1445)
> 
> IANAL. However, AFAIK it would violate Datadog's Apache 2 License.
> 
> References:
> 
> * [open-telemetry/community#113 (comment)](https://github.com/open-telemetry/community/issues/113#issuecomment-619116668)
> * https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#copyright-notices

We did this to align with our company-wide Open Source guidance so I'm sure that this is fine inside the `DataDog/dd-trace-dotnet` repo. I don't know what adjustments would need to be made to or if the change can even be accepted into this repo.

**Comment by pjanotti** [comment]
@zacharycmontoya and @pellared my reading is about the Notice not the copyright headers.  I will try to dig some info on this.

**Comment by pjanotti** [comment]
> Is there any easy way to:
>
> Know which integration test is hanging

.NET 5.0 to the rescue: new parameters `--blame-hang` and `--blame-hang-timeout`. Using 30s as timeout I had two tests in `Datadog.Trace.IntegrationTests.OriginTagSendTraces` exceeding that threshold. Skipping all tests for this class the tests completed on my Windows. I didn't have a chance yet to investigate to see the root cause.

**Comment by pellared** [comment]
I have noticed that the integration tests that are currently failing

```
[xUnit.net 00:02:10.04]     Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions [FAIL]
  Failed Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions [704 ms]
  Error Message:
   Non-success exit code -10
Expected: True
Actual:   False
  Stack Trace:
     at Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.SmokeTestBase.CheckForSmoke(Boolean shouldDeserializeTraces) in D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\SmokeTests\SmokeTestBase.cs:line 148
   at Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions() in D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\SmokeTests\AssemblyLoadFileNotFoundExceptionSmokeTest.cs:line 22
  Standard Output Messages:
 Application path: D:\a\1\s\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net5.0\AssemblyLoad.FileNotFoundException.dll
 Executable path: dotnet.exe
 Assigning port 55649 for the agentPort.
 Assigning port 55650 for the aspNetCorePort.
 Found profiler at D:\a\1\s\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net5.0\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll.
 Found integrations at D:\a\1\s\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net5.0\profiler-lib\integrations.json.
 StandardError:
 System.IO.FileNotFoundException: Could not load file or assembly 'OpenTelemetry.AutoInstrumentation.ClrProfiler.Managed, Version=0.0.1.0, Culture=neutral, PublicKeyToken=34b8972644a12429'. The system cannot find the file specified.
 File name: 'OpenTelemetry.AutoInstrumentation.ClrProfiler.Managed, Version=0.0.1.0, Culture=neutral, PublicKeyToken=34b8972644a12429'
    at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
    at AssemblyLoad.FileNotFoundException.Program.Main() in D:\a\1\s\test\test-applications\regression\AssemblyLoad.FileNotFoundException\Program.cs:line 16


[xUnit.net 00:01:30.03] Datadog.Trace.ClrProfiler.IntegrationTests: STARTED: Datadog.Trace.ClrProfiler.IntegrationTests.AdoNet.SystemDataSqliteTests.SpansDisabledByAdoNetExcludedTypes(True)
  Failed Datadog.Trace.ClrProfiler.IntegrationTests.AdoNet.SystemDataSqliteTests.SpansDisabledByAdoNetExcludedTypes(enableCallTarget: False) [1 s]
  Error Message:
   Process exited with code -532462766
Expected: True
Actual:   False
  Stack Trace:
     at Datadog.Trace.ClrProfiler.IntegrationTests.AdoNet.SystemDataSqliteTests.SpansDisabledByAdoNetExcludedTypes(Boolean enableCallTarget) in D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\AdoNet\SystemDataSqliteTests.cs:line 88
  Standard Output Messages:
 Platform: X64
 Configuration: Release
 TargetFramework: net461
 .NET Core: False
 Attempt 1: Unable to find profiler at D:\a\1\s\test/test-applications/integrations\Samples.SQLite.Core\bin\X64\Release\net461\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll.
 Found profiler at D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\bin\x64\Release\net461\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll.
 Profiler DLL: D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\bin\x64\Release\net461\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll
 Starting Application: D:\a\1\s\test/test-applications/integrations\Samples.SQLite.Core\bin\X64\Release\net461\Samples.SQLite.Core.exe
 Attempt 1: Unable to find integrations at D:\a\1\s\test/test-applications/integrations\Samples.SQLite.Core\bin\X64\Release\net461\profiler-lib\integrations.json.
 Found integrations at D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\bin\x64\Release\net461\profiler-lib\integrations.json.
 ProcessId: 448
 Exit Code: -532462766
 StandardError:
 
 Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
    at System.Data.SQLite.SQLite3.StaticIsInitialized()
    at System.Data.SQLite.SQLiteLog.Initialize(String className)
    at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
    at Samples.SQLite.Core.Program.OpenConnection()
    at Samples.SQLite.Core.Program.<Main>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at Samples.SQLite.Core.Program.<Main>()
```

were also failing before (sic!): https://dev.azure.com/opentelemetry/pipelines/_build/results?buildId=3778&view=results after merging https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/182

Maybe the MSBuild version bump has caused the issues?

@zacharycmontoya @tonyredondo Have you encountered the same issue in Datadog repo?

**Comment by pellared** [comment]
Test failed:

```
[xUnit.net 00:00:13.43]     Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.HttpHandlerStackOverflowExceptionSmokeTest.NoExceptions [FAIL]
  Failed Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.HttpHandlerStackOverflowExceptionSmokeTest.NoExceptions [11 s]
  Error Message:
   System.TimeoutException : The smoke test is running for too long or was lost.
```

Rerunning...

**Comment by pellared** [comment]
Only CodeQL Analysis workflow failed.

**Comment by pjanotti** [comment]
Long old discussion about copyright headers:

Starts here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/502#issuecomment-665798782

Conclusion at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/502#issuecomment-667212938

My reading is that we could update the headers as OTel but likely need someone from DD to merge this - let's discuss this on today's SIG meeting.

**Comment by pellared** [comment]
@zacharycmontoya 

From https://github.com/cncf/foundation/blob/master/copyright-notices.md#dont-change-someone-elses-notice-without-their-permission:

> You _should_ not change or remove someone else's copyright notice unless they have expressly permitted you to do so. This includes third parties' notices in pre-existing code.

I agree with @pjanotti statement here: 

> My reading is that we could update the headers as OTel but likely need someone from DD to merge/approve this - let's discuss this on today's SIG meeting.

I am just not sure what defines "expressly permitted" and "who" can do so. @iNikem can you help us?

**Comment by iNikem** [comment]
> > My reading is that we could update the headers as OTel but likely need someone from DD to merge/approve this - let's discuss this on today's SIG meeting.
> 
> I am just not sure what defines "expressly permitted" and "who" can do so. @iNikem do you know anything more regarding this topic?

If a maintainer from DD merges this PR with Otel License headers, that will mean that DD "expressly permitted" to replace DD attribution with Otel attribution.

**Review by zacharycmontoya — APPROVED** [review]

**Comment by zacharycmontoya** [comment]
At the last SIG meeting we decided that we would perform the OTEL license header changes in a later PR, and at that point one of the DD maintainers (such as myself) can merge that PR. Thanks for the info @iNikem 😄

**Pull request merged**
