### PR TITLE
Enable azure pipelines

### PR DESCRIPTION
**Pull request by pjanotti**
This adds the files needed to run the Azure Pipelines unit and integration tests. The only source changes is that for now I commented out the Alpine and Linus integration tests for .NET Core 2.1 and 3.0.

There are some flaky tests that failed in a few runs but this run completed all clean: https://github.com/pjanotti/opentelemetry-dotnet-instrumentation/pull/1/checks?check_run_id=1033829521

After this is merged I will enable Azure Pipelines for the repo.

### CODE REVIEW

**Comment by cijothomas** [comment]
Do you intend to migrate to GHActions in the future? Its much faster these days with more parallel builds :)

**Comment by pjanotti** [comment]
That is something that I want to look into but right now the original repo is using Azure Pipelines so just following the same here.

**Comment by eddynaka** [comment]
> That is something that I want to look into but right now the original repo is using Azure Pipelines so just following the same here.

ping me in gitter if u want to talk. Maybe i can help :)

**Comment by macrogreg** [comment]
Do we need the files in` /src/Datadog.Trace.MSBuild/ `they are an unrelated prototype for a feature that is not yet ready. Unless there is a need for them, can we please exclude them?

**Comment by macrogreg** [comment]
Same for files in `/src/Datadog.Trace.Ci.Shared/`.

**Comment by macrogreg** [comment]
Oh, just noticed that `Ci.Shared` is already in master, sorry. But not the `MSBuild` stuff.

**Comment by macrogreg** [comment]
Looks good otherwise. :)

**Comment by pjanotti** [comment]
`Datadog.Trace.proj` targets that `Datadog.Trace.MSBuild` project for the target `CreateHomeDirectory`
The CreateHomeDirectory is used by the sample apps in some of the integration tests.

**Comment by macrogreg** [comment]
Ah, I see. I did not realize it got integrated already. Let's be pragmatic them. Approved.

**Pull request merged**
