### PR TITLE
Release 1.8.0

### LINKED ISSUE #3624: Releasing 1.8.0
# Feature Request

Would like to ask if its possible to release 1.7.X to unblock the support per signal overrides

**Is your feature request related to a problem? Please describe.**
Currently, 1.7.0  doesn't support overriding the OTEL_EXPORTER_OTLP_ENDPOINT per signal.
For example, metrics url re-wiring is something that is relatively popular as there are multiple metrics ingestion projects that accepts the open telemetry protocol , and wiring to directly to them simplify infrastructure and eases adoption a lot.

Also its part of the Opentelemetry spec, and people that already adopted open telemetry in the past might find this discrepancy highly confusing and time consuming (its not documented as lacking in the dotnet auto instrumentation anywhere other than the unreleased Changelog here that implies it)

And lastly, no log to communicate this isn't supported whatsoever, and no log on getting 404/error from the unavailable global endpoint.

**Describe the solution you'd like**
patch release 1.7.X to unblock this feature

**Describe alternatives you've considered**
no clear alternatives for people requiring that change in the source (e.g not in Otel collector)

If this is not possible, it will be great to have some rough ETA on when 1.8.0 is expected if possible

Thanks 🙏

### PR DESCRIPTION
**Pull request by Kielek**
## Why

Fixes #3624

### Added

- Support for Operating System resource detector.
- Support for [RabbitMQ.Client](https://www.nuget.org/packages/RabbitMQ.Client/)
  traces instrumentation for versions `6.0.0`-`6.*.*`
- Support for NServiceBus 9.1+ metrics instrumentations.
- Added support for OTEL_TRACES_EXPORTER, OTEL_METRICS_EXPORTER, OTEL_LOGS_EXPORTER
  to handle comma-separated list.
- The environment variables `OTEL_TRACES_EXPORTER`, `OTEL_METRICS_EXPORTER`,
  and `OTEL_LOGS_EXPORTER` now support configuring console exporters for traces,
  metrics, and logs, respectively.
- Support signal specific OTLP exporter variables (See [docs](/docs/config.md#otlp)):
  - `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`,
  - `OTEL_EXPORTER_OTLP_TRACES_HEADERS`,
  - `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT`,
  - `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`,
  - `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT`,
  - `OTEL_EXPORTER_OTLP_METRICS_HEADERS`,
  - `OTEL_EXPORTER_OTLP_METRICS_TIMEOUT`,
  - `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`,
  - `OTEL_EXPORTER_OTLP_LOGS_ENDPOINT`,
  - `OTEL_EXPORTER_OTLP_LOGS_HEADERS`,
  - `OTEL_EXPORTER_OTLP_LOGS_TIMEOUT`,
  - `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL`.
- Support for air-gapped installations through `DOWNLOAD_DIR` or `LOCAL_PATH`
  arguments to `otel-dotnet-auto-install.sh`.
- Added `OTEL_DOTNET_AUTO_LOGGER` to select preferred sink for AutoInstrumentation
  diagnostic logs.
- Issue a warning before publish if auto-instrumentation NuGet
  package is referenced and runtime identifier is not specified.

### Changed

- More restrictive handling of invalid values in comma-separated lists.
  When invalid value is recognized (unsupported option, supported option
  with leading or trailing whitespaces, empty value, duplicate)
  warning is logged, and if `FailFast` is enabled, exception is thrown.
- Referencing `OpenTelemetry.AutoInstrumentation` manually no longer visibly injects
  instrumentation scripts into projects in an editor's solution window.

#### Dependency updates

- Following packages updated
  - `MongoDB.Driver.Core.Extensions.DiagnosticSources` from `1.4.0` to `1.5.0`,
  - `OpenTelemetry.Exporter.Prometheus.HttpListener` from `1.9.0-beta.1` to `1.9.0-beta.2`,
  - `OpenTelemetry.Instrumentation.Process` from `0.5.0-beta.6` to `0.5.0-beta.7`,
  - `OpenTelemetry.Resources.Azure` from `1.0.0-beta.8` to `1.0.0-beta.9`,
  - `OpenTelemetry.Resources.Host` from `0.1.0-beta.2` to `0.1.0-beta.3`,
  - `OpenTelemetry.Resources.Process` from `0.1.0-beta.2` to `0.1.0-beta.3`,
  - `OpenTelemetry.Shims.OpenTracing` from `1.9.0-beta.1` to `1.9.0-beta.2`.
- .NET only, following packages updated
  - `OpenTelemetry.Instrumentation.StackExchangeRedis` from `1.0.0-rc9.15` to `1.9.0-beta.1`.
- .NET Framework only, following packages updated
  - `Google.Protobuf` updated from `3.27.1` to `3.28.2`,
  - `Grpc.Core.Api` from `2.63.0` to `2.66.0`,
  - `Microsoft.Extensions.Configuration.Binder` from `8.0.1` to `8.0.2`,
  - `System.Text.Json` from `8.0.3` to `8.0.4`.

### Deprecated

- Environment variables `OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED`,
  `OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED`, and
  `OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED` are now marked as deprecated.

### Removed

- Support for macOS Big Sur 11 x64.
  macOs libraries are built and tested against [macOS Monterey 12 x64](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md).
- Support for `MongoDB.Driver.Core` < 2.28.0.
- Support for `StackExchange.Redis` < 2.6.122.

### Fixed

- Initialize WCF instrumentation only when necessary ([#3650](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3650))

## Tests

- [x] CI
- [x] MacOS with Linux Containers
- [x] Windows with Linux Containers

## Checklist

- [x] `CHANGELOG.md` is updated.
- [x] Documentation is updated.
- [x] New features are covered by tests.

### CODE REVIEW

**Comment by Kielek** [comment]
Tests fail locally for Windows: `RunManagedIntegratio: [xUnit.net 00:09:20.89]     IntegrationTests.MongoDBTests.SubmitsTraces(packageVersion: "2.29.0") [FAIL]`

From the logs:
```
[2024-09-26T06:23:46.2073304Z] [Debug] EventSource=OpenTelemetry-AutoInstrumentation-Loader, Message=Requester [<null>] requested [MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321] 
[2024-09-26T06:23:46.2920125Z] [Debug] EventSource=OpenTelemetry-AutoInstrumentation-Loader, Message=Requester [<null>] requested [MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321] 
[2024-09-26T06:23:46.3390112Z] [Error] Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321' or one of its dependencies. The system cannot find the file specified.
Exception: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321' or one of its dependencies. The system cannot find the file specified.
File name: 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at OpenTelemetry.AutoInstrumentation.Instrumentations.MongoDB.MongoClientIntegration.GetInstrumentationOptions()
   at OpenTelemetry.AutoInstrumentation.Instrumentations.MongoDB.MongoClientIntegration.GetClusterConfiguratorExpression()
   at OpenTelemetry.AutoInstrumentation.Instrumentations.MongoDB.MongoClientIntegration.OnMethodBegin[TTarget,TMongoClientSettings](TTarget instance, TMongoClientSettings settings)
   at OpenTelemetry.AutoInstrumentation.CallTarget.Handlers.BeginMethodHandler`3.Invoke(TTarget instance, TArg1& arg1)
   at MongoDB.Driver.MongoClient..ctor(MongoClientSettings settings)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Review by lachmatt — CHANGES_REQUESTED** [review]
Requires #3668

**Review by pjanotti — COMMENTED** [review]
After #3668 is merged it should be good to go

**Review by rajkumar-rangaraj — APPROVED** [review]

**Comment by Kielek** [comment]
> Tests fail locally for Windows: `RunManagedIntegratio: [xUnit.net 00:09:20.89] IntegrationTests.MongoDBTests.SubmitsTraces(packageVersion: "2.29.0") [FAIL]`
> 
> From the logs:
> 
> ```
> [2024-09-26T06:23:46.2073304Z] [Debug] EventSource=OpenTelemetry-AutoInstrumentation-Loader, Message=Requester [<null>] requested [MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321] 
> [2024-09-26T06:23:46.2920125Z] [Debug] EventSource=OpenTelemetry-AutoInstrumentation-Loader, Message=Requester [<null>] requested [MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321] 
> [2024-09-26T06:23:46.3390112Z] [Error] Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321' or one of its dependencies. The system cannot find the file specified.
> Exception: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321' or one of its dependencies. The system cannot find the file specified.
> System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321' or one of its dependencies. The system cannot find the file specified.
> File name: 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'
>    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
>    at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
>    at OpenTelemetry.AutoInstrumentation.Instrumentations.MongoDB.MongoClientIntegration.GetInstrumentationOptions()
>    at OpenTelemetry.AutoInstrumentation.Instrumentations.MongoDB.MongoClientIntegration.GetClusterConfiguratorExpression()
>    at OpenTelemetry.AutoInstrumentation.Instrumentations.MongoDB.MongoClientIntegration.OnMethodBegin[TTarget,TMongoClientSettings](TTarget instance, TMongoClientSettings settings)
>    at OpenTelemetry.AutoInstrumentation.CallTarget.Handlers.BeginMethodHandler`3.Invoke(TTarget instance, TArg1& arg1)
>    at MongoDB.Driver.MongoClient..ctor(MongoClientSettings settings)
> 
> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> ```
> 
> Will be discussed by #3668

Passed with fixes.

**Review by lachmatt — APPROVED** [review]

**Comment by pellared** [comment]
Passed on my macOS.

I had to made a little change to make the SqlClient passing: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3673. Not a blocker.

**Pull request merged**
