### PR TITLE
Release 0.3.0 beta.1

### PR DESCRIPTION
**Pull request by pjanotti**
## Why

Preparing release 0.3.0-beta.1

Part of  #1086

## What

- Update version in preparation for release 0.3.0-beta.1
- Update changelog

## Tests

In progress, will switch from Draft when completed.

## Checklist

- [X] `CHANGELOG.md` is updated.
- [X] Documentation is updated.
~~- [ ] New features are covered by tests.~~

### CODE REVIEW

**Comment by pjanotti** [comment]
One CI failure: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/7986124915?check_suite_focus=true#step:5:2272

**Comment by Kielek** [comment]
@pjanotti, for the commit with the tag version I think you should remove https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0a2664bc417a738482d0bdf8997603c109200b52/docs/README.md?plain=1#L8-L15

It should be restored when the tag is in place.

**Comment by pjanotti** [comment]
Regarding the failure on mac that I saw, see https://cloud-native.slack.com/archives/C01NR1YLSE7/p1661361338247289

Summary: it was due to an old version of netcoreapp3.1 - we have some minimum requirement regarding it.

**Comment by pjanotti** [comment]
@Kielek 

> @pjanotti, for the commit with the tag version I think you should remove ... It should be restored when the tag is in place.

I think it is ok to live with a broken link (already pointing to 0.3.0) for an small amount of time.

**Review by nrcventura — APPROVED** [review]

**Comment by Kielek** [comment]
> @Kielek
> 
> > @pjanotti, for the commit with the tag version I think you should remove ... It should be restored when the tag is in place.
> 
> I think it is ok to live with a broken link (already pointing to 0.3.0) for an small amount of time.

@pjanotti, it is not an issue for main branch, It is strange message on tagged version.

If you open
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.3.0-beta.1/docs/README.md?plain=1#L8-L15
You see information that it is develop branch. In fact it is tagged version which refers to itselff. It can introduce some missunderstanding for endusers.

**Pull request merged**
