### PR TITLE
Test nuget config workaround

### PR DESCRIPTION
**Pull request by vsafonkin**

### CODE REVIEW

**Comment by pellared** [comment]
@vsafonkin do you need this PR or can you close it?

**Comment by zacharycmontoya** [comment]
By the way, this `install-dotnet.yml` file is not invoked via the current Azure DevOps pipelines, so I think this PR is a no-op. I think the root issue was already addressed by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/120

**Comment by pjanotti** [comment]
Closing this PR since the issue was already solved in #120

**Comment by vsafonkin** [comment]
@pellared, @zacharycmontoya, @pjanotti, sorry, I forgot to close it. I've just tried to run AzDo build without nuget.config and any workarounds. Thanks!

**Pull request closed without merging**
