### PR TITLE
Document the releasing process

### LINKED ISSUE #337: Document releasing process
We should document how we are going to publish the beta release.

### PR DESCRIPTION
**Pull request by pellared**
Fixes #337

Changes proposed in this pull request:
- Document the release process in `releasing.md`

### CODE REVIEW

**Review by pjanotti — COMMENTED** [review]
LGTM.

**Comment by pjanotti** [comment]
Perhaps to do after all doc PRs are merged: fix the casing of the markdown file names. Currently, some are upper case and others lower case, the reason is not clear. Perhaps only README.md should be the upper case all other files should be lower case. This casing puts README.md as the first file listed on the folder.

**Review by pjanotti — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]
LGTM

**Comment by pellared** [comment]
> Perhaps to do after all doc PRs are merged: fix the casing of the markdown file names. Currently, some are upper case and others lower case, the reason is not clear. Perhaps only README.md should be the upper case all other files should be lower case. This casing puts README.md as the first file listed on the folder.

I think that `README.md`, `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md`, `CHANGELOG.md` and `LICENSE`  are commonly uppercase. The rest could be lowercase. WDYT?

**Comment by pjanotti** [comment]
> I think that README.md, CONTRIBUTING.md, CODE_OF_CONDUCT.md, CHANGELOG.md and LICENSE are commonly uppercase. OTel [requires](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) to have also VERSIONING.md in the root. The rest could be lowercase. WDYT?

It kind of defeats the purpose of having the README in upper case but it is a "nit/organizational" issue, as long we have a convention to follow it is fine for me.

**Pull request merged**
