### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by lachmatt**
## Why & What

Release 1.6.0

- [Core components](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/VERSIONING.md#core-components): [`1.8.1`](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.8.1)
- `System.Diagnostics.DiagnosticSource`: [`8.0.0`](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/8.0.0)

### Changed

- To prevent sensitive information from leaking through query strings, the
  following instrumentations redact by default any value detected in query string
  components when building the `url.query` or the `url.full` attributes:
  `OpenTelemetry.Instrumentation.Http`, `OpenTelemetry.Instrumentation.AspNetCore`,
  `OpenTelemetry.Instrumentation.AspNet`. For example, `?key1=value1&key2=value2`
  becomes `?key1=Redacted&key2=Redacted`. You can customize this behavior through
  the environment variables. See the
  [instrumentation options](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/bd9cdf7ad204aa0ec5244f160c6cc98846df5938/docs/config.md#instrumentation-options) table for details.

#### Dependency updates

- Following packages updated
  - `OpenTelemetry.Instrumentation.Http` from `1.8.0` to `1.8.1`.
- .NET only, following packages updated
  - `Microsoft.Extensions.Configuration.Binder` from `8.0.0` to `8.0.1`,
  - `OpenTelemetry.Instrumentation.AspNetCore` from `1.8.0` to `1.8.1`.
- .NET Framework only, following packages updated
  - `OpenTelemetry.Instrumentation.AspNet` from `1.8.0-beta.1` to `1.8.0-beta.2`.

### Fixed

- Stop creating `receive` consumer spans for consume attempts that returned no message.
  For details, see [#3367](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3367)

## Checklist

- [x] `CHANGELOG.md` is updated.
- [x] Documentation is updated.
- [x] New features are covered by tests.

### CODE REVIEW

**Comment by pellared** [comment]
Can bump to 1.6.0 to indicate changes and new env vars?

**Comment by pellared** [comment]
Tests passed on macOS

**Comment by Kielek** [comment]
> Can bump to 1.6.0 to indicate changes and new env vars?

Yesterday, we have agreed that it should go as 1.5.1. Nothing change since this discussion.

**Comment by lachmatt** [comment]
Tests passed on Windows with Linux containers.

**Comment by pellared** [comment]
> Yesterday, we have agreed that it should go as 1.5.1. Nothing change since this discussion.

Sorry but I was distracted at this moment.

I think it can be frustrating for some users. I feel it is safer to make a minor bump.

**Comment by pellared** [comment]
For reference https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/versioning.md#minor-version-bump: 

> Minor version bump
> Most changes result in a minor version bump.
> - **Addition of new** functionality, **configuration**, or instrumentation library.
> Changes related to the instrumentation libraries:
> - **Change (can be breaking) in a supported instrumentation library's functionality or configuration.**

Releasing it as a patch bump would break our versioning policy.

**Comment by lachmatt** [comment]
> This needs to be a minor bump according to our versioning policy

Changed to 1.6.0

**Review by pellared — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by pjanotti — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Pull request merged**
