### PR TITLE
Release 0.3.1-beta.1

### PR DESCRIPTION
**Pull request by pjanotti**
## Why

Preparing release 0.3.1-beta.1

(No issue for this release)

## What

- Update version in preparation for release 0.3.1-beta.1
- Update changelog

## Tests

In progress, will switch from Draft when completed.

## Checklist

- [X] `CHANGELOG.md` is updated.
- [X] Documentation is updated.
~~- [ ] New features are covered by tests.~~

### CODE REVIEW

**Comment by pjanotti** [comment]
Well known failure with EventSource test, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/8258104731?check_suite_focus=true#step:4:3201 (issue #1154)

**Comment by pjanotti** [comment]
Another CI failure https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/8258471391?check_suite_focus=true#step:4:3243 similar to #1123

**Comment by pjanotti** [comment]
So far no issues besides the CI failures above, ready for review.

**Review by nrcventura — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]
LGTM, tests work in my windows environment.

**Pull request merged**
