### PR TITLE
Increase timeout in tests

### LINKED ISSUE #1260: Flaky test: IntegrationTests.SmokeTests.PrometheusExporter
The IntegrationTests.SmokeTests.PrometheusExporter test fails frequently without any metrics captured, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3100807847/jobs/5021491754#step:4:3423 for instance.

Another issue related to the same test was recently fixed via #1259

### PR DESCRIPTION
**Pull request by pellared**
## Why

I think this is caused b/c the machines on GH Actions are not that powerful and also because the Prometheus exporter caches the returned metrics for 10 seconds.

Fixes #1260

## What

Increase timeout in tests to give more chances to succeed.

## Tests

`verify-test` GH workflows for `PrometheusExporter` test:
- https://github.com/pellared/opentelemetry-dotnet-instrumentation/actions/runs/3104812761
- https://github.com/pellared/opentelemetry-dotnet-instrumentation/actions/runs/3104815626
- https://github.com/pellared/opentelemetry-dotnet-instrumentation/actions/runs/3104842753

and CI workflow 

`GraphQLTests` , `LogTests` still fails from time to time . I want to look at it tomorrow.

## Checklist

- [x] ~~`CHANGELOG.md` is updated.~~
- [x] ~~Documentation is updated.~~
- [x] ~~New features are covered by tests.~~

### CODE REVIEW

**Comment by Kielek** [comment]
Alternative approach, can we reduce cache timeout in Prometheus? In never version, it is set to `300` ms for AspNetCore, and probably, by mistake to no cache on HttpListener. See https://github.com/open-telemetry/opentelemetry-dotnet/issues/3679#issuecomment-1252172029

**Comment by pellared** [comment]
> Alternative approach, can we reduce cache timeout in Prometheus? In never version, it is set to `300` ms for AspNetCore, and probably, by mistake to no cache on HttpListener. See [open-telemetry/opentelemetry-dotnet#3679 (comment)](https://github.com/open-telemetry/opentelemetry-dotnet/issues/3679#issuecomment-1252172029)

I was thinking of it, but it would require adding an env var support on our side. First I want to validate if that would even help 😉

**Comment by pellared** [comment]
@Kielek PTAL https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1266

**Comment by Kielek** [comment]
Well, I would set 300 in this PR, then in follow up add env. value.

**Review by RassK — APPROVED** [review]

**Comment by pellared** [comment]
> Well, I would set 300 in this PR, then in follow-up add env. value.

I prefer to keep the same default as the SDK for consistency.

**Pull request merged**
