### PR TITLE
Update troubleshooting doc

### PR DESCRIPTION
**Pull request by RassK**
### What

Removes block of troubleshooting net core dependencies, as it's not valid.
* There is no way to change compile time direct dependency version.
* Additional deps corrects the version when there is no direct dependency.

@pellared suggested currently not to add details about build time fixing, to better estimate the scope of the issue.

### CODE REVIEW

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by nrcventura — APPROVED** [review]

**Review by pjanotti — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Comment by pellared** [comment]
Shouldn't we remove the line below as well?

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/71886b9befc4ca759529ec77440d35cf8759739a/docs/troubleshooting.md?plain=1#L19

**Comment by pellared** [comment]
I read the section below a few times and I am not sure if this is understandable: 

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0683f38542d85f671e6a174f2498665a7cf0f21b/docs/troubleshooting.md?plain=1#L22-L25

@nrcventura can you please double-check it and fix it as part of this PR if needed?

**Review by pellared — APPROVED** [review]
I left https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/623#issuecomment-1105775020 but it is not related to changes in this PR so it can be addressed separately if needed

**Comment by nrcventura** [comment]
> I read the section below a few times and I am not sure if this is understandable:
> 
> https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0683f38542d85f671e6a174f2498665a7cf0f21b/docs/troubleshooting.md?plain=1#L22-L25
> 
> @nrcventura can you please double-check it and fix it as part of this PR if needed?

I agree that it is confusing. I'm leaning towards merging this as is, and then following up. I'm still searching to see if there are better explanations that we can link to that explain how/why we are relying on the runtime package store.

**Pull request merged**
