### PR TITLE
Catchup to upstream prior to directory reorg

### PR DESCRIPTION
**Pull request by pjanotti**
Catches up to upstream prior to directp\ory reorg.

### CODE REVIEW

**Comment by pjanotti** [comment]
Closing and re-opening to try to clean EasyCLA...

**Comment by zacharycmontoya** [comment]
The currently failing unit test `Datadog.Trace.Tests.Sampling.RuleBasedSamplerTests.No_Registered_Rules_Uses_Legacy_Rates` has also been surfaced recently in the Datadog repo as flaky. We'll need to figure this out, but it should not block the merge

**Comment by zacharycmontoya** [comment]
winmerge-filecomparison

I did a recursive diff of the contents from the original Datadog commit and contents of this branch. The only differences I notice are docs files (whose wording was modified for OpenTelemetry) and the OpenTelemetry.DynamicActivityBinding directory. So overall this looks like the desired result

**Review by zacharycmontoya — APPROVED** [review]
This looks good. The diff I attached in the PR comments looks as expected, and the CI is also running as expected. Thanks for updating this @pjanotti !

**Comment by pjanotti** [comment]
Trying the EasyCLA again...

**Comment by pjanotti** [comment]
I'm going to try closing this PR and opening a new one from the same branch...

**Comment by pjanotti** [comment]
It seems related to this PR in particular: perhaps there is no way to preserve history in this case or it needs to come in smaller chunks.

**Comment by pjanotti** [comment]
Closing this one for good now since #26 was merged.

**Pull request closed without merging**
