### PR TITLE
Execute dependabot daily

### PR DESCRIPTION
**Pull request by Kielek**
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/487#discussion_r850146854

Changes proposed in this pull request:

Execute dependabot daily

### CODE REVIEW

**Comment by Kielek** [comment]
It fixes also https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/6028862011

**Review by lachmatt — APPROVED** [review]

**Comment by nrcventura** [comment]
Is daily too frequent of a cadence? In the rare case that one of these packages deploy a problematic version, and remove that version quickly, would this daily cadence cause us to unnecessarily depend on the problematic version?

**Comment by pjanotti** [comment]
That's a good Q @nrcventura - the flip side is another unlikely case: we publish a version that misses some security fix by a few days. No a big deal if we don't have NuGet packages but it is the downside of reducing the frequency.

**Comment by nrcventura** [comment]
> That's a good Q @nrcventura - the flip side is another unlikely case: we publish a version that misses some security fix by a few days. No a big deal if we don't have NuGet packages but it is the downside of reducing the frequency.

Would a daily "security" scan potentially cover that gap?

**Comment by RassK** [comment]
> > That's a good Q @nrcventura - the flip side is another unlikely case: we publish a version that misses some security fix by a few days. No a big deal if we don't have NuGet packages but it is the downside of reducing the frequency.
> 
> Would a daily "security" scan potentially cover that gap?

I guess it depends on the release cycle. The latter could be way too slow to benefit if it's not automated patch and release.

**Comment by Kielek** [comment]
I think that we should use dependabot just for notification that the newer version occurred. The decision if the upgrade is needed for current release is always on the dev side. What is more PRs usually take more than 1 day, so the scenario when the version will be shortly removed should not be the case.

I think that, we are discussing preferences, the current settings are (almost) fine, the reason for creating PRs was 2x 👍 in the previous PR :)

**Review by pjanotti — APPROVED** [review]

**Review by nrcventura — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Pull request merged**
