### PR TITLE
Allow to execute CopyAdditionalDeps more than one

### LINKED ISSUE #1395: Intermittent IOException from Target CopyAdditionalDeps in local environment
**CopyAdditionalDeps              Failed          0:09   // IOException: The file 'D:\opentelemetry-dotnet-instrumentation\bin\tracer-home\store\x64\netcoreapp3.1\mongodb.driver.core\2.13.3\runtimes\win\native\libzstd.dll' already exists.**

10:32:39 [ERR] Target CopyAdditionalDeps has thrown an exception
System.IO.IOException: The file 'D:\opentelemetry-dotnet-instrumentation\bin\tracer-home\store\x64\netcoreapp3.1\mongodb.driver.core\2.13.3\runtimes\win\native\libzstd.dll' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Build.<get_CopyAdditionalDeps>g__CopyNativeDependenciesToStore|90_4(AbsolutePath file, String depsJsonContent) in D:\opentelemetry-dotnet-instrumentation\build\nuke\Build.Steps.cs:line 429
   at Build.<>c.<get_CopyAdditionalDeps>b__90_3(AbsolutePath file) in D:\opentelemetry-dotnet-instrumentation\build\nuke\Build.Steps.cs:line 382
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Build.<get_CopyAdditionalDeps>b__90_1() in D:\opentelemetry-dotnet-instrumentation\build\nuke\Build.Steps.cs:line 378
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112

**Proposed Fix**
* Add overwrite flag to `File.Copy`

### PR DESCRIPTION
**Pull request by Kielek**
## Why

Fixes #1395

## What

Allow to execute CopyAdditionalDeps more than one

## Tests

Manual test.

## Checklist

- ~~[ ] `CHANGELOG.md` is updated.~~
- ~~[ ] Documentation is updated.~~
- ~~[ ] New features are covered by tests.~~

### CODE REVIEW

**Comment by pellared** [comment]
How about updating the "cleaning" stage (beginning of the target's action) which is currently  has only `AdditionalDepsDirectory.GlobFiles("**/*deps.json").ForEach(DeleteFile);`?

**Comment by Kielek** [comment]
> How about updating the "cleaning" stage (beginning of the target's action) which is currently has only `AdditionalDepsDirectory.GlobFiles("**/*deps.json").ForEach(DeleteFile);`?

IMO we should avoid (manual) cleanup as much as possible in building phase.
If you execute Clean task, whole folder should be removed.

It should improve our dev experience, typically there is nothing to override.

**Comment by pellared** [comment]
@Kielek `Clean` task should be used to prepare a clean environment. Still, individual targets should be idempotent (if possible). E.g. you do not have to remove the binaries each time before you execute `dotnet build`.

**Review by dszmigielski — APPROVED** [review]

**Comment by pellared** [comment]
Suppressed by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1401

**Pull request closed without merging**
