### PR TITLE
Directory Restructuring (#973)

### PR DESCRIPTION
**Pull request by pjanotti**
Simplify root directory and logically move directories for a more hierarchical structure. This PR implements the proposal outlined in https://github.com/DataDog/dd-trace-dotnet/issues/951.

Main changes include:
* Root directory now has the following directories:
    - blog
    - build
    - docs
    - samples
    - src
    - test
    - tools
* The build directory now holds release artifacts, docker files / scripts, and C# projects that are used to maintain the build files.
* The samples directory now holds non-product related code that was originally in the customer-samples directory, so that users can see the product in action.
* The src directory now holds the WindowsInstaller project so all source files needed for the product build are in the src directory.
* The test/test-applications directory is now the root directory for all test applications, with the two main flavors being `integrations` and `regression`. This significantly reduces the number of directories at the root.

### CODE REVIEW

**Comment by pjanotti** [comment]
Bring Zach's commit doing the folder re-org. @zacharycmontoya you need to sign the EasyCLA.

**Comment by zacharycmontoya** [comment]
The Alpine test is failing on a MessagePack serialization issue. I believe it is this issue: https://github.com/DataDog/dd-trace-dotnet/pull/996 , so you may want to port commit https://github.com/DataDog/dd-trace-dotnet/commit/32cd0c17b9f5091c5c0d96d373164a056a079306

**Comment by zacharycmontoya** [comment]
The unit-test pipeline hasn't changed at all, so maybe that is a transient issue with regard to container bring 🤔 Either way, that is related to some trace collection we are running in CI that's sending to Datadog so we should remove it in a subsequent PR

**Comment by zacharycmontoya** [comment]
For other reviewers, to get an idea of what the result is, you can check out the https://github.com/datadog/dd-trace-dotnet to see that there is less clutter and folders in the root directory

**Comment by pjanotti** [comment]
Failure log:
```terminal
2020-10-30T17:15:44.0741829Z ##[command]/usr/bin/docker network create --label 40c6bc vsts_network_7a198d6a31134d2e8bf437b752d32d5a
2020-10-30T17:15:44.1554147Z a4b15d657d2e40a24ad5a4c0ccea2c3dfa4ddbe838ce94b95280eca1cad6d7c5
2020-10-30T17:15:44.1895283Z ##[command]/usr/bin/docker create --name dd_agent_dev_linux_datadogagentdevolivielpeaucicontainerdefaultspy3_f8b455 --label 40c6bc --network vsts_network_7a198d6a31134d2e8bf437b752d32d5a --network-alias dd_agent -p 8126:8126  -e "DD_API_KEY=$(DD_API_KEY)" -e "DD_INSIDE_CI=true" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/agents/2.175.2/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" datadog/agent-dev:olivielpeau-ci-container-defaults-py3
2020-10-30T17:15:50.7837473Z bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:50.7860740Z ##[command]/usr/bin/docker start bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:51.4012258Z bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:51.4110678Z ##[command]/usr/bin/docker ps --all --filter id=bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
2020-10-30T17:15:51.4763433Z bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e Up Less than a second (health: starting)
2020-10-30T17:15:51.4810759Z ##[command]/usr/bin/docker port bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:51.5331269Z 8126/tcp -> 0.0.0.0:8126
2020-10-30T17:15:51.5471489Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:51.6217414Z starting
2020-10-30T17:15:51.6283422Z dd_agent service is starting, waiting 2 seconds before checking again.
2020-10-30T17:15:53.6282060Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:53.6846824Z starting
2020-10-30T17:15:53.6873723Z dd_agent service is starting, waiting 3 seconds before checking again.
2020-10-30T17:15:57.6528456Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:15:57.6950328Z starting
2020-10-30T17:15:57.6980637Z dd_agent service is starting, waiting 6 seconds before checking again.
2020-10-30T17:16:04.4995235Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:16:04.5454184Z starting
2020-10-30T17:16:04.5472999Z dd_agent service is starting, waiting 15 seconds before checking again.
2020-10-30T17:16:19.9206568Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:16:19.9686694Z starting
2020-10-30T17:16:19.9735728Z dd_agent service is starting, waiting 28 seconds before checking again.
2020-10-30T17:16:48.7266842Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:16:49.3041608Z starting
2020-10-30T17:16:49.3057276Z dd_agent service is starting, waiting 32 seconds before checking again.
2020-10-30T17:17:21.3054200Z ##[command]/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" bf6871b15c347427237d3fcd080498d891081c4902f5517f54efd0aa0d11e76e
2020-10-30T17:17:21.8150324Z unhealthy
2020-10-30T17:17:21.8307160Z ##[error]Failed to initialize, dd_agent service is unhealthy.
2020-10-30T17:17:21.8322516Z ##[section]Finishing: Initialize containers
```

**Review by nrcventura — APPROVED** [review]
Looks good assuming we can figure out what's going on with the dd_agent service.

**Comment by nrcventura** [comment]
The dd_agent service failing to start applies to other PRs too, so it doesn't seem related to anything in this PR.

**Pull request merged**
