### PR TITLE
docs: Debug .NET Runtime on Linux

### PR DESCRIPTION
**Pull request by pellared**
## Why

A few months ago it took me ~2 days to figure everything out.

## What

Describe how one can debug the .NET Profiler on Linux.

### CODE REVIEW

**Review by rajkumar-rangaraj — APPROVED** [review]
LGTM. These steps will definitely help people identify an issue in shorter span of time.

**Review by RassK — APPROVED** [review]
Looks great. Just wondering if you want to leave your private paths on to the doc?
eg: '/home/rpajak/...'

**Comment by pellared** [comment]
> Looks great. Just wondering if you want to leave your private paths on to the doc? eg: '/home/rpajak/...'

not a problem for me but I will change it to `user` 😄

**Review by pjanotti — APPROVED** [review]
Thanks for this @pellared! LGTM.

**Review by nrcventura — APPROVED** [review]
Thanks for sharing this knowledge!

**Pull request merged**
