### PR TITLE
bump fmt to 10.0.0 

### LINKED ISSUE #2638: Update fmtlib to 10.0.0 release or newer.
Update fmtlib to 10.0.0 release or newer.

It can be separate issue.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2635#discussion_r1226347697_

### PR DESCRIPTION
**Pull request by basit9958**
## Why

Fixes #2638 

## What

Fmt updated from  9.1.0 to 10.0.0 
## Checklist

- [ ] `CHANGELOG.md` is updated.
- [ ] Documentation is updated.
- [ ] New features are covered by tests.

### CODE REVIEW

**Review by Kielek — CHANGES_REQUESTED** [review]
Blocking due to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2638#issuecomment-1586967593

**Comment by basit9958** [comment]
cc @Kielek

**Comment by Kielek** [comment]
@basit9958, pipeline is failing.

**Comment by basit9958** [comment]
> @basit9958, pipeline is failing.
Is it due to spdlog? I will talk with rassk about this on slack

**Comment by RassK** [comment]
> > @basit9958, pipeline is failing.
> > Is it due to spdlog? I will talk with rassk about this on slack

spdlog compilation is failing. fmt is dependency of spdlog, so spdlog must support also newer version.
Also I guess both must be updated in the same time, look at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1822

**Comment by RassK** [comment]
Seems there is no fmt 10.0 support yet.
https://github.com/gabime/spdlog/releases/tag/v1.11.0

**Comment by Kielek** [comment]
Closing due to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2685#issuecomment-1611139396

**Comment by Kielek** [comment]
#3160. Closing.

**Pull request closed without merging**
